name       : libwpg
version    : 0.3.1
release    : 1
source     :
    - http://pilotfiber.dl.sourceforge.net/project/libwpg/libwpg/libwpg-0.3.1/libwpg-0.3.1.tar.xz : 620d888c10d7e1127d5123ff0065f1b62b86b91bac27d8ae10dcfbdb6bf4278f
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : A library for import of WordPerfect Graphics images
description: |
    A library for import of WordPerfect Graphics images.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - pkgconfig(libwpd-0.10)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
