name       : libwpg
version    : 0.3.3
release    : 2
source     :
    - https://pilotfiber.dl.sourceforge.net/project/libwpg/libwpg/libwpg-0.3.3/libwpg-0.3.3.tar.xz : 99b3f7f8832385748582ab8130fbb9e5607bd5179bebf9751ac1d51a53099d1c
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : A library for import of WordPerfect Graphics images
description: |
    A library for import of WordPerfect Graphics images.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - pkgconfig(libwpd-0.10)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
